version: "3.9"

services:
  backend:
    container_name: "counter-service"
    build:
      context: .
    command: "/usr/local/bin/counter-service --config=/usr/src/app/cmd/counter/local_config.yaml"
    restart: always
    ports:
      - "8060:8060"
      - "8061:8061"
      - "7040:7040"
    volumes:
      - .:/usr/src/app
#    depends_on:
#      redis:
#        condition: service_healthy
    networks:
      - counter_net
#      - social-network_social_network_net
    external_links:
      - backend:backend
  redis:
    build:
      context: infra/redis
      dockerfile: Dockerfile
    container_name: redis
    image: redis:7.2.5
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data
    networks:
      - counter_net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  redis-data:

networks:
  counter_net:
    driver: bridge
#  social-network_social_network_net:
#    external: true
