// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.3
// source: internalapi/counter_service.proto

package internalapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CounterService_CreateDialogCounters_FullMethodName       = "/counter.internalapi.CounterService/CreateDialogCounters"
	CounterService_IncreaseDialogCounters_FullMethodName     = "/counter.internalapi.CounterService/IncreaseDialogCounters"
	CounterService_FlushDialogCountersForUser_FullMethodName = "/counter.internalapi.CounterService/FlushDialogCountersForUser"
	CounterService_GetDialogCounterForUser_FullMethodName    = "/counter.internalapi.CounterService/GetDialogCounterForUser"
)

// CounterServiceClient is the client API for CounterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CounterServiceClient interface {
	CreateDialogCounters(ctx context.Context, in *CreateDialogCountersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	IncreaseDialogCounters(ctx context.Context, in *IncreaseDialogCountersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FlushDialogCountersForUser(ctx context.Context, in *FlushDialogCountersForUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetDialogCounterForUser(ctx context.Context, in *GetDialogCounterForUserRequest, opts ...grpc.CallOption) (*GetDialogCounterForUserResponse, error)
}

type counterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCounterServiceClient(cc grpc.ClientConnInterface) CounterServiceClient {
	return &counterServiceClient{cc}
}

func (c *counterServiceClient) CreateDialogCounters(ctx context.Context, in *CreateDialogCountersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CounterService_CreateDialogCounters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) IncreaseDialogCounters(ctx context.Context, in *IncreaseDialogCountersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CounterService_IncreaseDialogCounters_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) FlushDialogCountersForUser(ctx context.Context, in *FlushDialogCountersForUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, CounterService_FlushDialogCountersForUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *counterServiceClient) GetDialogCounterForUser(ctx context.Context, in *GetDialogCounterForUserRequest, opts ...grpc.CallOption) (*GetDialogCounterForUserResponse, error) {
	out := new(GetDialogCounterForUserResponse)
	err := c.cc.Invoke(ctx, CounterService_GetDialogCounterForUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CounterServiceServer is the server API for CounterService service.
// All implementations must embed UnimplementedCounterServiceServer
// for forward compatibility
type CounterServiceServer interface {
	CreateDialogCounters(context.Context, *CreateDialogCountersRequest) (*emptypb.Empty, error)
	IncreaseDialogCounters(context.Context, *IncreaseDialogCountersRequest) (*emptypb.Empty, error)
	FlushDialogCountersForUser(context.Context, *FlushDialogCountersForUserRequest) (*emptypb.Empty, error)
	GetDialogCounterForUser(context.Context, *GetDialogCounterForUserRequest) (*GetDialogCounterForUserResponse, error)
	mustEmbedUnimplementedCounterServiceServer()
}

// UnimplementedCounterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCounterServiceServer struct {
}

func (UnimplementedCounterServiceServer) CreateDialogCounters(context.Context, *CreateDialogCountersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDialogCounters not implemented")
}
func (UnimplementedCounterServiceServer) IncreaseDialogCounters(context.Context, *IncreaseDialogCountersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncreaseDialogCounters not implemented")
}
func (UnimplementedCounterServiceServer) FlushDialogCountersForUser(context.Context, *FlushDialogCountersForUserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FlushDialogCountersForUser not implemented")
}
func (UnimplementedCounterServiceServer) GetDialogCounterForUser(context.Context, *GetDialogCounterForUserRequest) (*GetDialogCounterForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDialogCounterForUser not implemented")
}
func (UnimplementedCounterServiceServer) mustEmbedUnimplementedCounterServiceServer() {}

// UnsafeCounterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CounterServiceServer will
// result in compilation errors.
type UnsafeCounterServiceServer interface {
	mustEmbedUnimplementedCounterServiceServer()
}

func RegisterCounterServiceServer(s grpc.ServiceRegistrar, srv CounterServiceServer) {
	s.RegisterService(&CounterService_ServiceDesc, srv)
}

func _CounterService_CreateDialogCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDialogCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).CreateDialogCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_CreateDialogCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).CreateDialogCounters(ctx, req.(*CreateDialogCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_IncreaseDialogCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncreaseDialogCountersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).IncreaseDialogCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_IncreaseDialogCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).IncreaseDialogCounters(ctx, req.(*IncreaseDialogCountersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_FlushDialogCountersForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushDialogCountersForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).FlushDialogCountersForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_FlushDialogCountersForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).FlushDialogCountersForUser(ctx, req.(*FlushDialogCountersForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CounterService_GetDialogCounterForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDialogCounterForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CounterServiceServer).GetDialogCounterForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CounterService_GetDialogCounterForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CounterServiceServer).GetDialogCounterForUser(ctx, req.(*GetDialogCounterForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CounterService_ServiceDesc is the grpc.ServiceDesc for CounterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CounterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "counter.internalapi.CounterService",
	HandlerType: (*CounterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDialogCounters",
			Handler:    _CounterService_CreateDialogCounters_Handler,
		},
		{
			MethodName: "IncreaseDialogCounters",
			Handler:    _CounterService_IncreaseDialogCounters_Handler,
		},
		{
			MethodName: "FlushDialogCountersForUser",
			Handler:    _CounterService_FlushDialogCountersForUser_Handler,
		},
		{
			MethodName: "GetDialogCounterForUser",
			Handler:    _CounterService_GetDialogCounterForUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internalapi/counter_service.proto",
}
